apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 'external-credentials'
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: 'the/credentials'
        version: '2'
  refreshInterval: 0s
  secretStoreRef:
    kind: SecretStore
    name: 'vault-secretstore'
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: 'external-credentials'
