apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: 'greaterorequal-test-pdb'
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: 'greaterorequal-test'